version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      - pip install poetry==1.8.2
      - poetry config virtualenvs.create false
    post_install:
      - poetry install --without dev
      - poetry run python -m ipykernel install --user

sphinx:
  configuration: docs/conf.py
