version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      - pip install poetry==1.8.2
    post_install:
      # See https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-poetry
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --all-extras --without dev
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry run python -m ipykernel install --user

sphinx:
  configuration: docs/conf.py
