name: CI

on:
  push:
    branches:
      - \#4-add-github-actions
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python with pip cache
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip

      - name: Install Poetry
        run: pipx install poetry==1.3.2 --python $(which python)

      - run: which poetry
      - run: pipx --help

      - name: Set up Python with Poetry cache
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: poetry

      # - name: Install dependencies
      #   run: poetry install

      # - name: Check Formatting (Black)
      #   run: poetry run black paramdb tests --check

      # - name: Lint (Flake8)
      #   run: poetry run flake8 paramdb tests

      # - name: Lint (Pylint)
      #   run: poetry run pylint paramdb tests

      # - name: Mypy cache
      #   uses: actions/cache@v3
      #   with:
      #     path: .mypy_cache
      #     key: mypy-cache-${{ runner.os }}-python-3.10-${{ github.sha }}
      #     restore-keys: |
      #       mypy-cache-${{ runner.os }}-python-3.10-

      # - name: Type Check (Mypy)
      #   run: poetry run mypy paramdb tests

      # - name: Test (Pytest)
      #   run: poetry run pytest paramdb tests
