name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  POETRY_VERSION: "1.8.3"
  POETHEPOET_VERSION: "0.27.0"
  MAIN_PYTHON_VERSION: "3.9"
  PACKAGE_NAME: "paramdb"

jobs:
  ci:
    strategy:
      matrix:
        python_version: ["3.9", "3.10", "3.11", "3.12"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Poetry
        run: |
          pipx install poetry==${{ env.POETRY_VERSION }}
          pipx inject poetry poethepoet==${{ env.POETHEPOET_VERSION }}

      - name: Set up Python with Poetry cache
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
          cache: poetry

      - name: Install dependencies
        run: poetry install --all-extras --without docs

      - name: Mypy cache
        if: matrix.python_version == env.MAIN_PYTHON_VERSION
        uses: actions/cache@v4
        with:
          path: .mypy_cache
          key: mypy-${{ runner.os }}-python-${{ matrix.python_version }}-${{ github.sha }}
          restore-keys: |
            mypy-${{ runner.os }}-python-${{ matrix.python_version }}-

      - name: Lint
        if: matrix.python_version == env.MAIN_PYTHON_VERSION
        run: poetry lint

      - name: Test
        if: matrix.python_version != env.MAIN_PYTHON_VERSION
        run: poetry test

      - name: Test with coverage
        if: matrix.python_version == env.MAIN_PYTHON_VERSION
        run: poetry test --cov=${{ env.PACKAGE_NAME }} --cov-report=xml

      - name: Upload coverage reports to Codecov
        if: matrix.python_version == env.MAIN_PYTHON_VERSION
        uses: codecov/codecov-action@v4
