name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.10"
  POETRY_VERSION: "1.5.1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry==${{ env.POETRY_VERSION }}

      - name: Build package
        run: poetry build

      - name: Upload package artifact
        uses: actions/upload-artifact@v3
        with:
          name: paramdb-dist
          path: dist

  publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/paramdb
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: paramdb-dist

      - name: Display structure of downloaded files
        run: ls -R
